### ISSUE TITLE
Embed: Viewer does not work on sandboxed iframe.

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-server#307] opened 2021-06-23 14:33 UTC
As reported here -> https://speckle.community/t/3d-models-visuals-in-power-bi/1429/6

What I think is happening is that the `iframe` is being automatically loaded with the `sandbox` attribute, which means extra security rules apply.

Tried hacking it by adding the `allow-same-origin` attribute but same happens. We should look further into this, as I'm sure its not the only platform that will do this.

**Comment by teocomi** [comment] 2021-06-24 10:53
Dupe of https://github.com/specklesystems/speckle-server/issues/289

**Closed** 2021-06-28 10:56 UTC
Labels: [ Frontend - Main App ]
