### ISSUE TITLE
App Authorization page to display currently logged user

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-server#92] opened 2021-02-02 19:02 UTC
The App Authorization page should display the currently logged user (if any) and provide a way to log out / switch accounts.
Right now it just prompts the user to approve or deny access:

![image](https://user-images.githubusercontent.com/2679513/106648941-d812cb00-6588-11eb-955f-d0e3ce6fc79d.png)

**Comment by didimitrie** [comment] 2021-02-02 19:04
dupe of #74 😎

**Closed by didimitrie** 2021-02-02 19:04 UTC
Labels: [ Frontend - Auth Lock ], enhancement
