### ISSUE TITLE
Viewer slow MacOS + firefox

### ISSUE THREAD

**Issue by gjedlicska** [specklesystems/speckle-server#1155] opened 2022-10-28 10:26 UTC
This [sample stream](https://latest.speckle.dev/streams/914b292235) on MacOS 12.6 **firefox** causes the usual system wide slowdown

**Comment by AlexandruPopovici** [comment] 2023-01-19 17:30
I can't reproduce this on my Mac in Firefox. Closing for now, will re-open if required

**Closed by AlexandruPopovici** 2023-01-19 17:30 UTC
Labels: bug, [ viewer ]
