### ISSUE TITLE
`objectsender` Incorrect lib export

### ISSUE THREAD

**Issue by vwnd** [specklesystems/speckle-server#2487] opened 2024-07-10 07:03 UTC
I think there's something wrong with the library typescript export/mapping on the build configuration.

The code works, but I have no Typescript exposed (1):
![image](https://github.com/specklesystems/speckle-server/assets/61347148/3e501d8c-2ec8-46ec-adb7-a8311284153f)

As I would expect this (2):
![image](https://github.com/specklesystems/speckle-server/assets/61347148/7530ecc7-0686-43d8-8123-0a4b27a6067c)

My project is not that big so I can quickly swap the imports between (1) and (2) during dev and build. But it would be nice if this could be fixed. Let me know if you want me to have a look at it. Builds are something intimate 😄 so I won't touch anything unless you think I should.

**Comment by cdriesler** [comment] 2024-07-12 13:47
Can confirm and reproduce! It looks like the latest release has shipped without types in `/dist`, will see what happened.

**Comment by cdriesler** [comment] 2024-07-15 17:48
@vwnd This has been addressed in the latest release `2.20.1`, let me know if that's not the case for you. Thank you for flagging!

**Closed by cdriesler** 2024-07-15 17:48 UTC
Labels: bug
